export const PALETTE = {
  DARK_GREY: '#2C2F2E',
  ORANGE: '#D65727',
  LIGHT_GREY: '#909191',
  LSW_ORANGE: '#D05539',
  PURPLE: '#4D34DB',
  GREEN: '#4C8446',
  RED: '#FB0000',
}

export const COLOR = {
  BASE_ACCENT: PALETTE.PURPLE,
  BASE_BACKGROUND: PALETTE.WHITE,
  BASE_FONT: PALETTE.BLACK,
  LINK_FONT: PALETTE.BLACK,
  ...PALETTE,
}
